In [1]:
import numpy as np
import pandas as pd

## Bag-of-Words

In [3]:
import pandas as pd

df = pd.DataFrame({
    "text": [
        "The cat sat on the mat",
        "Cats are very curious animals",
        "The quick brown fox jumps over the lazy dog.",
        "Dogs are loyal and friendly pets",
        "I love reading books on a rainy day",
        "Artificial Intelligence is transforming the future of technology",
        "Machine Learning and AI are closely related fields",
        "Python is a popular programming language for data science",
        "Data visualization helps make complex information easy to understand",
        "Deep learning techniques are revolutionizing image and language processing"
    ],
    "output": [1, 1, 0, 0, 1, 1, 1, 1, 0, 0]
})

df


text  output
0                             The cat sat on the mat       1
1                      Cats are very curious animals       1
2       The quick brown fox jumps over the lazy dog.       0
3                   Dogs are loyal and friendly pets       0
4                I love reading books on a rainy day       1
5  Artificial Intelligence is transforming the fu...       1
6  Machine Learning and AI are closely related fi...       1
7  Python is a popular programming language for d...       1
8  Data visualization helps make complex informat...       0
9  Deep learning techniques are revolutionizing i...       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


In [5]:
bow = cv.fit_transform(df['text'])

In [7]:
#vocabulary
print(cv.vocabulary_)

{'the': 54, 'cat': 7, 'sat': 50, 'on': 38, 'mat': 36, 'cats': 8, 'are': 3, 'very': 58, 'curious': 11, 'animals': 2, 'quick': 45, 'brown': 6, 'fox': 20, 'jumps': 28, 'over': 39, 'lazy': 30, 'dog': 15, 'dogs': 16, 'loyal': 33, 'and': 1, 'friendly': 21, 'pets': 40, 'love': 32, 'reading': 47, 'books': 5, 'rainy': 46, 'day': 13, 'artificial': 4, 'intelligence': 26, 'is': 27, 'transforming': 56, 'future': 22, 'of': 37, 'technology': 53, 'machine': 34, 'learning': 31, 'ai': 0, 'closely': 9, 'related': 48, 'fields': 18, 'python': 44, 'popular': 41, 'programming': 43, 'language': 29, 'for': 19, 'data': 12, 'science': 51, 'visualization': 59, 'helps': 23, 'make': 35, 'complex': 10, 'information': 25, 'easy': 17, 'to': 55, 'understand': 57, 'deep': 14, 'techniques': 52, 'revolutionizing': 49, 'image': 24, 'processing': 42}


In [8]:
bow.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0, 0, 0, 

In [9]:
X = bow.toarray()
y = df['output']

# Ngrams

In [10]:
df = pd.DataFrame({
    "text": [
        "The cat sat on the mat",
        "Cats are very curious animals",
        "The quick brown fox jumps over the lazy dog.",
        "Dogs are loyal and friendly pets",
        "I love reading books on a rainy day",
        "Artificial Intelligence is transforming the future of technology",
        "Machine Learning and AI are closely related fields",
        "Python is a popular programming language for data science",
        "Data visualization helps make complex information easy to understand",
        "Deep learning techniques are revolutionizing image and language processing"
    ],
    "output": [1, 1, 0, 0, 1, 1, 1, 1, 0, 0]
})

df


text  output
0                             The cat sat on the mat       1
1                      Cats are very curious animals       1
2       The quick brown fox jumps over the lazy dog.       0
3                   Dogs are loyal and friendly pets       0
4                I love reading books on a rainy day       1
5  Artificial Intelligence is transforming the fu...       1
6  Machine Learning and AI are closely related fi...       1
7  Python is a popular programming language for d...       1
8  Data visualization helps make complex informat...       0
9  Deep learning techniques are revolutionizing i...       0

In [11]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [12]:
bow = cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'the cat': 55, 'cat sat': 11, 'sat on': 53, 'on the': 43, 'the mat': 58, 'cats are': 12, 'are very': 7, 'very curious': 62, 'curious animals': 15, 'the quick': 59, 'quick brown': 48, 'brown fox': 10, 'fox jumps': 22, 'jumps over': 31, 'over the': 44, 'the lazy': 57, 'lazy dog': 34, 'dogs are': 19, 'are loyal': 5, 'loyal and': 38, 'and friendly': 2, 'friendly pets': 23, 'love reading': 37, 'reading books': 50, 'books on': 9, 'on rainy': 42, 'rainy day': 49, 'artificial intelligence': 8, 'intelligence is': 28, 'is transforming': 30, 'transforming the': 61, 'the future': 56, 'future of': 24, 'of technology': 41, 'machine learning': 39, 'learning and': 35, 'and ai': 1, 'ai are': 0, 'are closely': 4, 'closely related': 13, 'related fields': 51, 'python is': 47, 'is popular': 29, 'popular programming': 45, 'programming language': 46, 'language for': 32, 'for data': 21, 'data science': 16, 'data visualization': 17, 'visualization helps': 63, 'helps make': 25, 'make complex': 40, 'complex inf

In [15]:
# Ti gram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [16]:
bow = cv.fit_transform(df['text'])

In [17]:
print(cv.vocabulary_)

{'the cat sat': 47, 'cat sat on': 11, 'sat on the': 45, 'on the mat': 37, 'cats are very': 12, 'are very curious': 7, 'very curious animals': 52, 'the quick brown': 50, 'quick brown fox': 42, 'brown fox jumps': 10, 'fox jumps over': 20, 'jumps over the': 28, 'over the lazy': 38, 'the lazy dog': 49, 'dogs are loyal': 17, 'are loyal and': 5, 'loyal and friendly': 33, 'and friendly pets': 2, 'love reading books': 32, 'reading books on': 43, 'books on rainy': 9, 'on rainy day': 36, 'artificial intelligence is': 8, 'intelligence is transforming': 25, 'is transforming the': 27, 'transforming the future': 51, 'the future of': 48, 'future of technology': 21, 'machine learning and': 34, 'learning and ai': 30, 'and ai are': 1, 'ai are closely': 0, 'are closely related': 4, 'closely related fields': 13, 'python is popular': 41, 'is popular programming': 26, 'popular programming language': 39, 'programming language for': 40, 'language for data': 29, 'for data science': 19, 'data visualization help

In [18]:
bow = bow.toarray()

In [19]:
bow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# TF-IDF

In [20]:
df = pd.DataFrame({
    "text": [
        "The cat sat on the mat",
        "Cats are very curious animals",
        "The quick brown fox jumps over the lazy dog.",
        "Dogs are loyal and friendly pets",
        "I love reading books on a rainy day",
        "Artificial Intelligence is transforming the future of technology",
        "Machine Learning and AI are closely related fields",
        "Python is a popular programming language for data science",
        "Data visualization helps make complex information easy to understand",
        "Deep learning techniques are revolutionizing image and language processing"
    ],
    "output": [1, 1, 0, 0, 1, 1, 1, 1, 0, 0]
})

df


text  output
0                             The cat sat on the mat       1
1                      Cats are very curious animals       1
2       The quick brown fox jumps over the lazy dog.       0
3                   Dogs are loyal and friendly pets       0
4                I love reading books on a rainy day       1
5  Artificial Intelligence is transforming the fu...       1
6  Machine Learning and AI are closely related fi...       1
7  Python is a popular programming language for d...       1
8  Data visualization helps make complex informat...       0
9  Deep learning techniques are revolutionizing i...       0

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [24]:
ar = tfid.fit_transform(df['text'])

In [27]:
print(tfid.vocabulary_)

{'the': 54, 'cat': 7, 'sat': 50, 'on': 38, 'mat': 36, 'cats': 8, 'are': 3, 'very': 58, 'curious': 11, 'animals': 2, 'quick': 45, 'brown': 6, 'fox': 20, 'jumps': 28, 'over': 39, 'lazy': 30, 'dog': 15, 'dogs': 16, 'loyal': 33, 'and': 1, 'friendly': 21, 'pets': 40, 'love': 32, 'reading': 47, 'books': 5, 'rainy': 46, 'day': 13, 'artificial': 4, 'intelligence': 26, 'is': 27, 'transforming': 56, 'future': 22, 'of': 37, 'technology': 53, 'machine': 34, 'learning': 31, 'ai': 0, 'closely': 9, 'related': 48, 'fields': 18, 'python': 44, 'popular': 41, 'programming': 43, 'language': 29, 'for': 19, 'data': 12, 'science': 51, 'visualization': 59, 'helps': 23, 'make': 35, 'complex': 10, 'information': 25, 'easy': 17, 'to': 55, 'understand': 57, 'deep': 14, 'techniques': 52, 'revolutionizing': 49, 'image': 24, 'processing': 42}


In [22]:
arr = tfid.fit_transform(df['text']).toarray()

In [23]:
arr

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.41047121, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.41047121, 0.        , 0.34893803, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.41047121, 0.        , 0.        , 0.        , 0.61055909,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.47472745, 0.31390347, 0.        ,
        0.        , 0.        , 0.        , 0.47472745, 0.        ,
        0.        , 0.47472745, 0.        , 0. 